-- 코드를 입력하세요
SELECT *
FROM (
    SELECT a.ANIMAL_ID, a.NAME
    FROM ANIMAL_INS a
    JOIN ANIMAL_OUTS b
      ON a.ANIMAL_ID = b.ANIMAL_ID
    ORDER BY (b.DATETIME - a.DATETIME) DESC
)
WHERE ROWNUM <= 2;